M48
; DRILL file {KiCad (6.0.5-0)} date Monday, June 20, 2022 at 08:48:49 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-20T08:48:49-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X6.5156Y-3.8438
X6.75Y-2.3438
X14.0156Y-2.3438
X14.0156Y-3.8438
X14.8594Y-1.9688
T0
M30
