M48
; DRILL file {KiCad (6.0.5-0)} date Tuesday, June 14, 2022 at 05:56:38 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-14T17:56:38-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X6.5156Y-3.8438
X6.75Y-2.3438
X14.0156Y-2.3438
X14.0156Y-3.8438
T0
M30
