M48
; DRILL file {KiCad (6.0.1-0)} date Monday, April 18, 2022 at 09:34:52 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-18T21:34:52-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0098
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X15.2571Y-2.3674
T2
X14.8594Y-1.9688
T0
M30
